import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Title, Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-investors-page',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="investors-page">
      <section class="hero">
        <div class="container">
          <p class="section-label">FOR INVESTORS</p>
          <h1>Investing in Digital Trust</h1>
          <p class="hero-subtitle">
            TruWit is building the verification infrastructure for the AI era, solving the authenticity crisis in digital media.
          </p>
        </div>
      </section>

      <section class="problem">
        <div class="container">
          <h2>The Problem</h2>
          <div class="problem-stats">
            <div class="stat-card">
              <div class="stat-number">$78B</div>
              <p>Lost annually to digital misinformation</p>
            </div>
            <div class="stat-card">
              <div class="stat-number">90%</div>
              <p>Of online content will be AI-generated by 2026</p>
            </div>
            <div class="stat-card">
              <div class="stat-number">500M+</div>
              <p>Deepfake videos circulating online</p>
            </div>
          </div>
        </div>
      </section>

      <section class="solution">
        <div class="container">
          <h2>Our Solution</h2>
          <p class="section-description">
            TruWit provides cryptographic proof of content authenticity, enabling creators, platforms, and enterprises to verify digital media provenance in seconds.
          </p>
          
          <div class="solution-grid">
            <div class="solution-card">
              <h3>🎯 Massive Market</h3>
              <p>Content authenticity market projected to reach $15B by 2028, growing at 35% CAGR.</p>
            </div>
            <div class="solution-card">
              <h3>💡 Unique Technology</h3>
              <p>C2PA-compliant verification with proprietary perceptual hashing and AI detection.</p>
            </div>
            <div class="solution-card">
              <h3>📈 Strong Traction</h3>
              <p>Growing user base across creators, media organizations, and enterprises.</p>
            </div>
            <div class="solution-card">
              <h3>🌐 Network Effects</h3>
              <p>Every verification strengthens the platform, creating a trust network.</p>
            </div>
          </div>
        </div>
      </section>

      <section class="opportunity">
        <div class="container">
          <h2>Investment Opportunity</h2>
          <div class="opportunity-content">
            <p>
              We're raising capital to scale our infrastructure, expand our AI detection capabilities, and accelerate enterprise adoption.
            </p>
            <p>
              Join us in building the trust layer for digital media. For investor inquiries, please contact:
            </p>
            <a href="mailto:hello&#64;truwit.ai" class="contact-email">hello&#64;truwit.ai</a>
          </div>
        </div>
      </section>

      <section class="team">
        <div class="container">
          <h2>Leadership Team</h2>
          <p class="section-description">
            Our team combines deep expertise in cryptography, AI, and media technology with a track record of building scalable platforms.
          </p>
        </div>
      </section>

      <section class="cta">
        <div class="container">
          <h2>Join Our Journey</h2>
          <p>Help us build trust in the age of AI</p>
          <a href="mailto:hello&#64;truwit.ai" class="btn-primary">Contact Us</a>
        </div>
      </section>
    </div>
  `,
  styles: [`
    .investors-page {
      min-height: 100vh;
      background: var(--bg-0);
      color: var(--text-primary);
    }

    .hero {
      padding: 3rem 0 2rem;
      text-align: center;
    }

    .section-label {
      color: var(--teal);
      font-size: 0.875rem;
      font-weight: 600;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      margin-bottom: 0.5rem;
    }

    .container {
      max-width: var(--w-container);
      margin: 0 auto;
      padding: 0 1.5rem;
    }

    h1 {
      font-size: clamp(2rem, 4vw, 2.5rem);
      font-weight: 700;
      margin: 0 0 1rem 0;
    }

    h2 {
      font-size: 2rem;
      font-weight: 700;
      margin: 0 0 2rem 0;
      text-align: center;
    }

    .hero-subtitle {
      font-size: 1.1rem;
      color: var(--text-secondary);
      max-width: 700px;
      margin: 0 auto;
      line-height: 1.6;
    }

    .section-description {
      font-size: 1.1rem;
      color: var(--text-secondary);
      max-width: 800px;
      margin: 0 auto 2rem;
      text-align: center;
      line-height: 1.6;
    }

    .problem {
      padding: 4rem 0;
      background: rgba(255, 255, 255, 0.02);
    }

    .problem-stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 2rem;
      margin-top: 2rem;
    }

    .stat-card {
      text-align: center;
      padding: 2rem;
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: var(--radius);
    }

    .stat-number {
      font-size: 3rem;
      font-weight: 700;
      color: var(--teal);
      margin-bottom: 1rem;
    }

    .stat-card p {
      color: var(--text-secondary);
      font-size: 1.1rem;
      margin: 0;
    }

    .solution {
      padding: 4rem 0;
    }

    .solution-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 2rem;
      margin-top: 2rem;
    }

    .solution-card {
      padding: 2rem;
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: var(--radius);
      transition: all 0.3s ease;
    }

    .solution-card:hover {
      transform: translateY(-4px);
      border-color: rgba(14, 165, 233, 0.3);
      box-shadow: 0 10px 30px rgba(14, 165, 233, 0.1);
    }

    .solution-card h3 {
      font-size: 1.25rem;
      font-weight: 600;
      margin: 0 0 1rem 0;
    }

    .solution-card p {
      color: var(--text-secondary);
      line-height: 1.6;
      margin: 0;
    }

    .opportunity {
      padding: 4rem 0;
      background: rgba(255, 255, 255, 0.02);
    }

    .opportunity-content {
      max-width: 700px;
      margin: 0 auto;
      text-align: center;
    }

    .opportunity-content p {
      font-size: 1.1rem;
      color: var(--text-secondary);
      line-height: 1.6;
      margin-bottom: 1.5rem;
    }

    .contact-email {
      display: inline-block;
      font-size: 1.5rem;
      color: var(--teal);
      text-decoration: none;
      font-weight: 600;
      margin-top: 1rem;
    }

    .contact-email:hover {
      text-decoration: underline;
    }

    .team {
      padding: 4rem 0;
    }

    .cta {
      padding: 4rem 0;
      text-align: center;
      background: linear-gradient(135deg, var(--bg-1) 0%, var(--bg-2) 100%);
    }

    .cta h2 {
      font-size: 2rem;
      font-weight: 700;
      margin: 0 0 1rem 0;
    }

    .cta p {
      font-size: 1.1rem;
      color: var(--text-secondary);
      margin: 0 0 2rem 0;
    }

    .btn-primary {
      display: inline-block;
      padding: 0.875rem 2rem;
      background: var(--teal);
      color: var(--bg-0);
      text-decoration: none;
      border-radius: var(--radius);
      font-weight: 600;
      transition: all 0.2s ease;
    }

    .btn-primary:hover {
      background: #13c4bc;
      transform: translateY(-2px);
      box-shadow: 0 10px 30px rgba(20, 212, 201, 0.3);
    }

    @media (max-width: 768px) {
      .problem-stats,
      .solution-grid {
        grid-template-columns: 1fr;
      }

      .stat-number {
        font-size: 2.5rem;
      }
    }
  `]
})
export class InvestorsPageComponent implements OnInit {
  constructor(
    private title: Title,
    private meta: Meta
  ) {}

  ngOnInit(): void {
    this.title.setTitle('For Investors - TruWit');
    this.meta.updateTag({ name: 'description', content: 'Learn about TruWit\'s mission to build digital trust and investment opportunities in content authenticity.' });
  }
}

