import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { Title, Meta } from '@angular/platform-browser';

@Component({
  selector: 'app-investors-page',
  standalone: true,
  imports: [CommonModule, RouterModule],
  styleUrls: ['./investors-page.component.scss'],
  template: `
    <div class="investors-page">
      <section class="hero">
        <div class="container">
          <p class="section-label">FOR INVESTORS</p>
          <h1>Investing in Digital Trust</h1>
          <p class="hero-subtitle">
            TruWit is building the verification infrastructure for the AI era, solving the authenticity crisis in digital media.
          </p>
        </div>
      </section>

      <section class="problem">
        <div class="container">
          <h2>The Problem</h2>
          <div class="problem-stats">
            <div class="stat-card">
              <div class="stat-number">$78B</div>
              <p>Lost annually to digital misinformation</p>
            </div>
            <div class="stat-card">
              <div class="stat-number">90%</div>
              <p>Of online content will be AI-generated by 2026</p>
            </div>
            <div class="stat-card">
              <div class="stat-number">500M+</div>
              <p>Deepfake videos circulating online</p>
            </div>
          </div>
        </div>
      </section>

      <section class="solution">
        <div class="container">
          <h2>Our Solution</h2>
          <p class="section-description">
            TruWit provides cryptographic proof of content authenticity, enabling creators, platforms, and enterprises to verify digital media provenance in seconds.
          </p>
          
          <div class="solution-grid">
            <div class="solution-card">
              <h3>🎯 Massive Market</h3>
              <p>Content authenticity market projected to reach $15B by 2028, growing at 35% CAGR.</p>
            </div>
            <div class="solution-card">
              <h3>💡 Unique Technology</h3>
              <p>C2PA-compliant verification with proprietary perceptual hashing and AI detection.</p>
            </div>
            <div class="solution-card">
              <h3>📈 Strong Traction</h3>
              <p>Growing user base across creators, media organizations, and enterprises.</p>
            </div>
            <div class="solution-card">
              <h3>🌐 Network Effects</h3>
              <p>Every verification strengthens the platform, creating a trust network.</p>
            </div>
          </div>
        </div>
      </section>

      <section class="opportunity">
        <div class="container">
          <h2>Investment Opportunity</h2>
          <div class="opportunity-content">
            <p>
              We're raising capital to scale our infrastructure, expand our AI detection capabilities, and accelerate enterprise adoption.
            </p>
            <p>
              Join us in building the trust layer for digital media. For investor inquiries, please contact:
            </p>
            <a href="mailto:hello&#64;truwit.ai" class="contact-email">hello&#64;truwit.ai</a>
          </div>
        </div>
      </section>

      <section class="team">
        <div class="container">
          <h2>Leadership Team</h2>
          <p class="section-description">
            Our team combines deep expertise in cryptography, AI, and media technology with a track record of building scalable platforms.
          </p>
        </div>
      </section>

      <section class="cta">
        <div class="container">
          <h2>Join Our Journey</h2>
          <p>Help us build trust in the age of AI</p>
          <a href="mailto:hello&#64;truwit.ai" class="btn-primary">Contact Us</a>
        </div>
      </section>
    </div>
  `
})
export class InvestorsPageComponent implements OnInit {
  constructor(
    private title: Title,
    private meta: Meta
  ) {}

  ngOnInit(): void {
    this.title.setTitle('For Investors - TruWit');
    this.meta.updateTag({ name: 'description', content: 'Learn about TruWit\'s mission to build digital trust and investment opportunities in content authenticity.' });
  }
}
