// <auto-generated />
using System;
using HumanProof.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanProof.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251005205827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("License")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LikenessConsent")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("VerificationMetadata");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerceptualHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MetadataId")
                        .IsUnique();

                    b.HasIndex("ProofId")
                        .IsUnique();

                    b.ToTable("VerificationProofs");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProofId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProofId");

                    b.HasIndex("Status");

                    b.ToTable("VerificationRequests");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationProof", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.VerificationMetadata", "Metadata")
                        .WithOne("Proof")
                        .HasForeignKey("HumanProof.Api.Domain.Entities.VerificationProof", "MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationRequest", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.VerificationProof", "Proof")
                        .WithMany()
                        .HasForeignKey("ProofId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proof");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationMetadata", b =>
                {
                    b.Navigation("Proof")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
