// <auto-generated />
using System;
using HumanProof.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HumanProof.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024035949_AddMultiSignSchema")]
    partial class AddMultiSignSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Asset", b =>
                {
                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("Bytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DurationSec")
                        .HasColumnType("double precision");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("MediaType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("AssetId");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.AssetFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long?>("Bytesize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Mime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("FileId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_assetfile_group");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("AssetFiles");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.AssetGroup", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("PHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("PHashAlgo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("phash-dct");

                    b.Property<int>("PHashBits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(64);

                    b.HasKey("GroupId");

                    b.HasIndex("PHash")
                        .HasDatabaseName("ix_assetgroup_phash");

                    b.ToTable("AssetGroups");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Identity", b =>
                {
                    b.Property<Guid>("IdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AccountCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<string>("Handle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdentityId");

                    b.HasIndex("Provider", "Handle")
                        .IsUnique();

                    b.ToTable("Identities", t =>
                        {
                            t.HasCheckConstraint("CK_Identity_Provider", "\"Provider\" IN ('x', 'google', 'github', 'behance', 'anon')");
                        });
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.LinkIndex", b =>
                {
                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CanonicalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProofId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Platform", "CanonicalId");

                    b.ToTable("LinkIndex");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.ManifestEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.HasKey("EventId");

                    b.HasIndex("GroupId");

                    b.ToTable("ManifestEvents");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Proof", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AssetId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("C2paJson")
                        .HasColumnType("text");

                    b.Property<bool>("C2paPresent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MetadataId")
                        .HasColumnType("text");

                    b.Property<string>("OriginStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyJson")
                        .HasColumnType("text");

                    b.Property<string>("PolicyResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProofCardLargeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProofCardSmallUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReceiptId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrustmarkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("TrustmarkId")
                        .IsUnique();

                    b.ToTable("Proofs");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Receipt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<string>("ProofId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReceiptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<string>("SignerPubKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProofId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.ServiceSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("Key");

                    b.ToTable("ServiceSettings");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Signature", b =>
                {
                    b.Property<Guid>("SigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("ClientPublicKey")
                        .HasColumnType("bytea");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("SigBlob")
                        .HasColumnType("bytea");

                    b.Property<string>("SignatureType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("eddsa");

                    b.Property<DateTime>("SignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("StatementJson")
                        .HasColumnType("jsonb");

                    b.HasKey("SigId");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_signature_file");

                    b.HasIndex("IdentityId")
                        .HasDatabaseName("ix_signature_identity");

                    b.HasIndex("FileId", "IdentityId")
                        .IsUnique();

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("License")
                        .HasColumnType("integer");

                    b.Property<string>("LikenessConsent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Prompt")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ToolName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("VerificationMetadata");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationProof", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerceptualHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProofCardLargeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProofCardSmallUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProofId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MetadataId")
                        .IsUnique();

                    b.HasIndex("ProofId")
                        .IsUnique();

                    b.ToTable("VerificationProofs");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProofId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProofId");

                    b.HasIndex("Status");

                    b.ToTable("VerificationRequests");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.AssetFile", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.AssetGroup", "Group")
                        .WithMany("Files")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.ManifestEvent", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.AssetGroup", "Group")
                        .WithMany("ManifestEvents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Signature", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.AssetFile", "File")
                        .WithMany("Signatures")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanProof.Api.Domain.Entities.Identity", "Identity")
                        .WithMany("Signatures")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationProof", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.VerificationMetadata", "Metadata")
                        .WithOne("Proof")
                        .HasForeignKey("HumanProof.Api.Domain.Entities.VerificationProof", "MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationRequest", b =>
                {
                    b.HasOne("HumanProof.Api.Domain.Entities.VerificationProof", "Proof")
                        .WithMany()
                        .HasForeignKey("ProofId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proof");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.AssetFile", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.AssetGroup", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("ManifestEvents");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.Identity", b =>
                {
                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("HumanProof.Api.Domain.Entities.VerificationMetadata", b =>
                {
                    b.Navigation("Proof")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
